### ISSUE TITLE
Download button bringing up upload window

### ISSUE THREAD

**Issue by chivoX** [GenaroNetwork/GenaroEden_Client#4]
this is happening on the master branch
![screen shot 2018-02-08 at 6 46 30 pm](https://user-images.githubusercontent.com/2006403/36004377-7543a604-0d00-11e8-9972-4dec8cf5eac2.png)
![screen shot 2018-02-08 at 6 46 39 pm](https://user-images.githubusercontent.com/2006403/36004387-7e8c784e-0d00-11e8-9fbc-68dfd960a7a7.png)

**Comment by flowfire** [comment]
This is a download popup window which means you can choose a path and store your file(s).

**Comment by chivoX** [comment]
oh ok, thanks. so that will send all the selected files to the desired folder, ok.
