### ISSUE TITLE
Genaro Eden application nothing function

### ISSUE THREAD

**Issue by stone89son** [GenaroNetwork/GenaroEden_Client#7]
Dear Genaro Network Developer 
I just downloaded the "Genaro.Eden.Setup.1.2.1.exe" and installed it.
Once installed, run the Genaro Eden application. 
But the application does not have any function?

![setup](https://user-images.githubusercontent.com/6795515/37463036-513da2f2-2897-11e8-9aad-2b206108a898.PNG)

**Comment by NOCTLJRNE** [comment]
I have the same issue too

**Comment by seekerlee** [comment]
What's you windows version? 32 bit or 64 bit? currently we only support 64 bit, win7 and after

**Comment by stone89son** [comment]
Dear.
My enviroment:
Window 7 64 bit.

**Comment by NOCTLJRNE** [comment]
mine is windows 10 64 bits. 
I also had problems running Genaro Eden on Ubuntu, after download the file from https://genaro.network/download/Genaro-Eden.zip, I extracted it on my x86_64 ubuntu machine, ran the preinstall_unix.sh, then tried to run the genaro binary, but it gave the error "cannot execute binary file : Exec format error"

**Comment by stone89son** [comment]
Show Developer Tool. show bug
![development mode](https://user-images.githubusercontent.com/6795515/37519774-bdcd6ecc-295d-11e8-92f1-b83d8fcf9e8b.PNG)

**Comment by seekerlee** [comment]
Some windows missing msvcr110.dll which is required.
Please try https://github.com/GenaroNetwork/GenaroEden_Client/releases/tag/v1.2.2-Beta which fixed this problem.
 Feel free to reopen if not working.

**Comment by stone89son** [comment]
it working thank you.

**Comment by NOCTLJRNE** [comment]
it worked !

**Comment by stone89son** [comment]
working only. There are many bugs, please try, we believe in you
